name: Test Java

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Set up Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - run: sdkmanager "ndk;21.4.7075529"
      - run: sdkmanager "cmake;3.10.2.4988404"
      - shell: bash
        run: mkdir toolchains
      - name: specify NDK
        uses: ravinderjangra/android-ndk-toolchain-setup@0.2
        with:
          api: '21'
          arch: 'x86'
          install-location: 'toolchains'
          force: true
      - name: Test
        run: make test-java
