name: Test Java

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./java

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Set up Java 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Test
        run: make test-java
