name: Test Java

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Set up Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - run: sdkmanager "ndk;17.2.4988734"
      - run: sdkmanager "cmake;3.10.2.4988404"
      - name: Test
        run: make test-java
